name: build binary

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: egor-tensin/setup-clang@v1
              with:
                  version: latest
                  platform: x64
            - run: chmod +x ./make.sh && ./make.sh && ./out/main
